from typing import Callable, Sequence

from .param import RSDriverParam

_PointCloudCallback = Callable[[int, int, int, float, Sequence[Sequence[float]]], None]
_ExceptionCallback = Callable[[int, str], None]

class PyRSDriver:
    def init(self, py_param: RSDriverParam) -> bool: ...
    def start(self) -> bool: ...
    def stop(self) -> None: ...
    def regPointCloudCallback(self, fn: _PointCloudCallback) -> None: ...
    def regExceptionCallback(self, fn: _ExceptionCallback) -> None: ...
    def getLidarTemperature(self, fn) -> float: ...
    def displayNativeMsg(self, flag: bool) -> None: ...
